# Generated by Django 5.2.7 on 2025-12-11 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={},
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='passenger',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('notification_type', models.CharField(choices=[('ride_requested', 'Ride Requested'), ('ride_offered', 'Ride Offered'), ('ride_accepted', 'Ride Accepted'), ('ride_rejected', 'Ride Rejected'), ('ride_completed', 'Ride Completed'), ('ride_cancelled', 'Ride Cancelled')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rides.ride')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='rides_notif_user_id_bd4950_idx'), models.Index(fields=['user_id', 'is_read'], name='rides_notif_user_id_4ce912_idx')],
            },
        ),
    ]
