# Generated by Django 5.2.7 on 2025-11-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='role',
            field=models.CharField(choices=[('passager', 'Passager'), ('chauffeur', 'Chauffeur')], default='passager', max_length=30),
        ),
    ]
